### ISSUE TITLE
Rename lwrp to `default`

### ISSUE THREAD

**Issue by josegonzalez** [ooyala/tarball-chef-cookbook#1]
This would allow users to run `tarball` instead of `tarball_x`. I can make a PR, just curious if there was a reason why it was named `x`.

**Comment by irabinovitch** [comment]
Happy to take a PR.  We should probably support both for backwards compatibility.

**Comment by josegonzalez** [comment]
Hmmm, not sure we can support both without duplicating the code. I'll see if an include works...

**Comment by kbruner** [comment]
I can look at it next week, too.  I wrote this late last year, before Chef12 was out, and hadn't touched it since.

**Comment by irabinovitch** [comment]
@kbruner  added this in #2
